plugins { id 'com.android.application' }

android {
    namespace 'com.shorthunter.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.shorthunter.app'
        minSdk 24
        targetSdk 35
        versionCode 5
        versionName '4.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
